### ISSUE TITLE
optirun don't work with any apps in chroot

### ISSUE THREAD

**Issue by Yrij-Zhavoronkov** [Bumblebee-Project/Bumblebee#897]
ON host (Debian testing::amd64):
`optirun -vv glxgears
[ 1087.032312] [DEBUG]Reading file: /etc/bumblebee/bumblebee.conf
[ 1087.032741] [INFO]Configured driver: nvidia
[ 1087.032995] [DEBUG]optirun version 3.2.1 starting...
[ 1087.033018] [DEBUG]Active configuration:
[ 1087.033026] [DEBUG] bumblebeed config file: /etc/bumblebee/bumblebee.conf
[ 1087.033035] [DEBUG] X display: :8
[ 1087.033042] [DEBUG] LD_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu/nvidia:/usr/lib/i386-linux-gnu/nvidia:/usr/lib/nvidia
[ 1087.033050] [DEBUG] Socket path: /var/run/bumblebee.socket
[ 1087.033057] [DEBUG] Accel/display bridge: primus
[ 1087.033077] [DEBUG] VGL Compression: proxy
[ 1087.033098] [DEBUG] VGLrun extra options: 
[ 1087.033123] [DEBUG] Primus LD Path: /usr/lib/x86_64-linux-gnu/primus:/usr/lib/i386-linux-gnu/primus:/usr/lib/primus:/usr/lib32/primus
[ 1088.074079] [INFO]Response: Yes. X is active.

[ 1088.074115] [INFO]Running application using primus.
[ 1088.074282] [DEBUG]Process glxgears started, PID 13669.
302 frames in 5.0 seconds = 60.284 FPS
primus: warning: dropping a frame to avoid deadlock
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 35 requests (35 known processed) with 0 events remaining.
primus: warning: dropping a frame to avoid deadlock
primus: warning: timeout waiting for display worker
[ 1098.207660] [DEBUG]SIGCHILD received, but wait failed with No child processes
[ 1098.207828] [DEBUG]Socket closed.
[ 1098.207912] [DEBUG]Killing all remaining processes.`

But on chroot (Debian testing::i386):

`optirun -vv glxgears
[  964.624455] [DEBUG]Reading file: /etc/bumblebee/bumblebee.conf
[  964.624998] [INFO]Configured driver: nvidia
[  964.625274] [DEBUG]optirun version 3.2.1 starting...
[  964.625297] [DEBUG]Active configuration:
[  964.625306] [DEBUG] bumblebeed config file: /etc/bumblebee/bumblebee.conf
[  964.625314] [DEBUG] X display: :8
[  964.625322] [DEBUG] LD_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu/nvidia:/usr/lib/i386-linux-gnu/nvidia:/usr/lib/nvidia
[  964.625331] [DEBUG] Socket path: /var/run/bumblebee.socket
[  964.625347] [DEBUG] Accel/display bridge: auto
[  964.625373] [DEBUG] VGL Compression: proxy
[  964.625397] [DEBUG] VGLrun extra options: 
[  964.625421] [DEBUG] Primus LD Path: /usr/lib/i386-linux-gnu/primus:/usr/lib/primus:/usr/lib32/primus
[  964.625522] [DEBUG]Using auto-detected bridge primus
[  965.666007] [INFO]Response: Yes. X is active.

[  965.666041] [INFO]Running application using primus.
[  965.666176] [DEBUG]Process glxgears started, PID 13596.
[  965.716443] [DEBUG]SIGCHILD received, but wait failed with No child processes
[  965.716482] [DEBUG]Socket closed.
[  965.716501] [DEBUG]Killing all remaining processes`
suddenly...App is die(

On Debian Stretch All was right.

**Comment by bluca** [comment]
Bumblebee, bbswitch, primus and the nvidia drivers are for all intent and purposes the same between stable and testing at this moment, so I would suggest investigating xorg-server which got a new point release.

**Comment by Yrij-Zhavoronkov** [comment]
Xorg? Странно, но приложения запущенные без optirun работают нормально.
Xorg? Strange.. application running without optirun works fine.

**Comment by bluca** [comment]
Just trying to triage it. Check the journal to see if there's anything useful.

**Comment by Yrij-Zhavoronkov** [comment]
ok. found this: glxgears[16775]: segfault at 0 ip           (null) sp 00000000ff98894c error 14 in glxgears[565cf000+5000]
in journalctl.

**Comment by bluca** [comment]
try to install the debug symbols for glxgears and run it in gdb, and see where the crash is

**Comment by Yrij-Zhavoronkov** [comment]
glxgears-dbg or mesa-utils-dbg... I can't see it on debian repo

**Comment by bluca** [comment]
mesa-utils-dbgsym

**Comment by Yrij-Zhavoronkov** [comment]
sid only, ok i probe it and add the result

**Comment by bluca** [comment]
no it's in stretch as well, but you need to add the debug repository: ```deb http://deb.debian.org/debian-debug/ stretch-debug main contrib non-free```

**Comment by bluca** [comment]
or the equivalent for buster

**Comment by Yrij-Zhavoronkov** [comment]
Hm... i'm don't understand
`(gdb) run
Starting program: /usr/bin/glxgears 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00000000 in ?? ()
(gdb) backtrace
#0  0x00000000 in ?? ()
#1  0xf796927e in futex_wake (private=0, processes_to_wake=2147483647, futex_word=0xf6db55e4) at ../sysdeps/unix/sysv/linux/futex-internal.h:231
#2  __pthread_once_slow (once_control=0xf6db55e4, init_routine=0xf6d28410) at pthread_once.c:127
#3  0xf6d28f67 in ?? () from /usr/lib/i386-linux-gnu/libGLX_nvidia.so.0
#4  0xf6cf12fc in ?? () from /usr/lib/i386-linux-gnu/libGLX_nvidia.so.0
#5  0xf7fe8c21 in call_init (l=0x565947e8, argc=argc@entry=1, argv=argv@entry=0xffffd6e4, env=0xffffd6ec) at dl-init.c:58
#6  0xf7fe8d8e in call_init (env=0xffffd6ec, argv=0xffffd6e4, argc=1, l=<optimized out>) at dl-init.c:30
#7  _dl_init (main_map=main_map@entry=0x565947e8, argc=1, argv=0xffffd6e4, env=0xffffd6ec) at dl-init.c:120
#8  0xf7fecf67 in dl_open_worker (a=<optimized out>) at dl-open.c:575
#9  0xf7fe8b11 in _dl_catch_error (objname=objname@entry=0xffffcee4, errstring=errstring@entry=0xffffcee8, mallocedp=mallocedp@entry=0xffffcee3, operate=0xf7fecba0 <dl_open_worker>, 
    args=0xffffceec) at dl-error.c:187
#10 0xf7fec759 in _dl_open (file=0x565946b0 "libGLX_nvidia.so.0", mode=-2147483647, caller_dlopen=0xf78440b5 <__glXLookupVendorByName+1669>, nsid=<optimized out>, argc=1, argv=0xffffd6e4, 
    env=0xffffd6ec) at dl-open.c:660
#11 0xf7922bf5 in dlopen_doit (a=0xffffd0a0) at dlopen.c:66
#12 0xf7fe8b11 in _dl_catch_error (objname=0x56578414, errstring=0x56578418, mallocedp=0x56578410, operate=0xf7922b80 <dlopen_doit>, args=0xffffd0a0) at dl-error.c:187
#13 0xf79232ed in _dlerror_run (operate=operate@entry=0xf7922b80 <dlopen_doit>, args=args@entry=0xffffd0a0) at dlerror.c:163
#14 0xf7922c9e in __dlopen (file=0x565946b0 "libGLX_nvidia.so.0", mode=1) at dlopen.c:87
#15 0xf78440b5 in __glXLookupVendorByName () from /usr/lib/i386-linux-gnu/libGLX.so.0
#16 0x00000001 in ?? ()
#17 0x565a2470 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) continue
Continuing.

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
`

**Comment by Yrij-Zhavoronkov** [comment]
and what to do?
